# Generated by Django 5.0.6 on 2024-05-21 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyusite', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sdcimage',
            new_name='Imij',
        ),
    ]
