# Generated by Django 5.0.6 on 2024-05-30 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyusite', '0002_rename_sdcimage_imij'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='show_title',
            field=models.BooleanField(default=False, help_text='If the title should be shown (if not blank)', verbose_name='show title'),
        ),
    ]
