# Generated by Django 5.0.6 on 2024-06-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyusite', '0003_alter_rack_show_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='is_special',
            field=models.BooleanField(default=False, help_text="If the section is special and thus won't be included in the regular loop"),
        ),
    ]
