# Generated by Django 5.0.6 on 2024-09-11 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyusite', '0004_section_is_special'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ('menu', 'order')},
        ),
    ]
